openapi: 3.0.3
info:
  title: Measurement Book APIs
  description: >
    APIs to create, modify and search measurement books. Measurement books
    contain a list of measurements against some baselines or reference values.
    Measurements can aid in assessing progress with respect to the baseline or
    reference values. 
  version: 1.0.0
  contact:
    name: eGov Foundation
    email: contact@egovernments.org
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
externalDocs:
  description: DIGIT Works Platform
  url: https://works.digit.org
tags:
  - name: MeasurementBook
    description: Endpoints for the measurement book registry
  - name: Measurement
    description: Endpoints for adding measurements to a measurement book
  - name: Measurement Services
    description: APIs to create measurements along with Workflow and other business services on top of the registry.
paths:
  /measurementbook/_create:
    post:
      summary: /mbook/_create
      description: Create a measurement book
      tags:
        - MeasurementBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MBRequest'
      responses:
        '202':
          description: Accepted create measurement book request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MBResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /measurementbook/_update:
    post:
      summary: /mbook/_update
      description: Update values in a measurement book
      tags:
        - MeasurementBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MBRequest'
      responses:
        '200':
          description: Accepted update measurement book request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MBResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /measurement/_create:
    post:
      summary: /measurement/_create
      description: Create one or more measurement entries
      tags:
        - Measurement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementRequest'
      responses:
        '202':
          description: Accepted create measurement request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MeasurementResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /measurement/_update:
    post:
      summary: /measurement/_update
      description: Update one or more measurement entries
      tags:
        - Measurement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementRequest'
      responses:
        '200':
          description: Accepted update measurement request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MeasurementResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /mbookservices/measurement/_create:
    post:
      summary: /mbookservices/measurement/_create
      description: Creates a measurement entry along with workflow details.
      tags:
        - Measurement Services
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementServiceRequest'
      responses:
        '202':
          description: Accepted create measurement book request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MeasurementServiceResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /mbookservices/measurement/_update:
    post:
      summary: /mbookservices/measurement/_update
      description: Update values in a measurement book
      tags:
        - Measurement Services
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementServiceRequest'
      responses:
        '200':
          description: Accepted update measurement book request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MeasurementServiceResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
                
components:
  schemas:
    MeasurementBook:
      type: object
      description: >-
        The mBook models a physical measurement book. An mBook is created with a
        list of items it is supposed to measure.
      properties:
        id:
          type: string
          description: Unique uuid for this measurement book
          format: uuid
          minLength: 2
          maxLength: 64
          readOnly: true
        mBookNumber:
          type: string
          description: Formatted number for the measurement book
          example: MB/2023-24/001
          minLength: 2
          maxLength: 64
        referenceId:
          type: string
          description: >-
            Reference to the entity this measurement book is related to.
            Example: contract number or id
          example: WO/2023-24/123
          minLength: 2
          maxLength: 64
        referenceUri:
          type: string
          description: Base path of entity or service related to this MB
          example: /contracts/
        fromPeriod:
          description: From date of validity period.Eg. validity of contract period.
          type: number
          format: timestamp
        toPeriod:
          description: To date of validity period.
          type: number
          format: timestamp
        isActive:
          type: boolean
        measurables:
          type: array
          description: >-
            List of items with reference values against which measurements will
            be made
          items:
            $ref: '#/components/schemas/MeasurableItem'
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any additional information that needs to be attached to the object.
            For attachments, fileStoreIds will also be stored here. 
      required:
        - id
    MeasurableItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          minLength: 2
          maxLength: 64
          readOnly: true
        referenceId:
          type: string
          description: ID of what is being measured
          example: contractLineItemID
          minLength: 2
          maxLength: 64
        name:
          type: string
          description: Description of lineitem or entity being measured
          example: Supply of one no. of street lamp post of 8ft length
          minLength: 2
          maxLength: 512
        value:
          type: string
          description: >-
            Expected or approved value for the item being measured. Can be a
            range or a value
        rate:
          type: number
          description: Approved rate of item if applicable
        uom:
          type: string
          description: Unit of measurement. Should be same as the reference.
          minLength: 2
          maxLength: 64
        uomValue:
          type: number
          description: Value of uom
        details:
          type: array
          description: >-
            Detailed measurement sheet, if any, for this item. Can have one or
            more entries
          items:
            $ref: '#/components/schemas/DetailedMeasurement'
        measurements:
          type: array
          description: Array of measurements for this item
          items:
            $ref: '#/components/schemas/Measurement'
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any additional information that needs to be attached to the object.
            For attachments, fileStoreIds will also be stored here. 
      required:
        - name
        - value
        - uom
        - uomValue
    Measurement:
      type: object
      properties:
        id:
          type: string
          description: Unique ID for measurement
          format: uuid
          minLength: 2
          maxLength: 64
        measurementNumber:
          type: string
          description: Formatted number for this entry
        referenceId:
          type: string
          description: >-
            Parent or related entity to which this measurement belongs. Eg. MB
            or contract
          example: measurementbookid, contractid
        targetId:
          type: string
          description: >-
            References the measurable item for which this measurement is being
            made.
          example: measurableItemId, contractlineitemid
        fromDate:
          type: number
          format: timestamp
        toDate:
          type: number
          format: timestamp
        cumulativeValue:
          type: number
          description: Cumulative value upto the current entry
        measuredValue:
          type: number
          description: Current measured value
        details:
          type: array
          items:
            $ref: '#/components/schemas/DetailedMeasurement'
        comments:
          type: string
          description: Any observational comments made during measurement
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any additional information that needs to be attached to the object.
            For attachments, fileStoreIds will also be stored here. 
      required:
        - id
        - measurementNumber
        - targetId
        - measuredValue
    DetailedMeasurement:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the detailed measurement entry
          format: uuid
          example: 251c51eb-e970-4e01-a99a-70136c47a934
          minLength: 2
          maxLength: 64
          readOnly: true
        referenceId:
          type: string
          example: measurementID
          description: The detailed measurement line item for which this entry exists
          minLength: 2
          maxLength: 64
        itemDescription:
          type: string
          description: Description of the measurement. What are we measuring?
          minLength: 2
          maxLength: 512
          pattern: ^[A-Za-z0-9\/ . _$@#]*$
          example: Left side wall of room
        isDeduction:
          type: boolean
          description: >-
            If it is a deduction, the quantity needs to be subtracted from the
            total.
          example: false
        numItems:
          type: number
          description: The number of items of the same type that will be measured
          example: 10
          default: 1
        measures:
          type: array
          description: 'Dimensional values used to measure this item. '
          items:
            $ref: '#/components/schemas/Measure'
        uom:
          type: string
          description: Unit of measurement master data.
          example: Celcius, PPM, meter, squaremeter, cubicmeter
          minLength: 2
          maxLength: 64
        uomValue:
          type: number
          description: Base qty for unit of measurement. Can be 1 or multiple
          example: 10kg, 1tonne
        totalQuantity:
          type: number
          description: >-
            Related to measures - if available - using a formula. Else can be
            entered directly. This is measured using the uom.
        isActive:
          type: boolean
          description: Flag used to soft delete entries
          default: true
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any additional information that needs to be attached to the
            estimate. For attachments, fileStoreIds will also be stored here.
      required:
        - referenceId
        - isDeduction
        - numItems
        - uom
        - uomValue
        - totalQuantity
    Measure:
      type: object
      description: >-
        Entity captures dimension being measured, unit of measurement and
        associated value.
      properties:
        label:
          type: string
          description: Measurement dimension. L or B or H
          example: length
          minLength: 2
          maxLength: 256
        value:
          type: number
          description: Value of the measure. Related to the uom.
          example: 10
        uom:
          type: string
          description: Unit of measurement master data.
          example: Kilogram, Meter, SquareMeter, CubicMeter, Celcius, ppm.
          minLength: 2
          maxLength: 64
        uomValue:
          type: number
          description: Base qty for unit of measurement. Can be 1 or multiple
          example: 10kg, 1tonne
        isActive:
          type: boolean
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any additional information that needs to be attached to the
            estimate. For attachments, fileStoreIds will also be stored here.
      required:
        - label
        - value
        - uom
    MeasurementExtended:
      type: object
      properties:
        allOf:
          $ref: '#/components/schemas/Measurement'
        workflow:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow'
    MBRequest:
      type: object
      description: Encapsulates a measurement book request
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        mBooks:
          type: array
          items:
            $ref: '#/components/schemas/MeasurementBook'
    MBResponse:
      type: object
      description: Encapsulates a MB response
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        mBooks:
          type: array
          items:
            $ref: '#/components/schemas/MeasurementBook'
    MeasurementRequest:
      type: object
      description: Encapsulates a measurement book entry request
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        measurements:
          type: array
          items:
            $ref: '#/components/schemas/Measurement'
          minItems: 1
    MeasurementResponse:
      type: object
      description: Encapsulates a measurement response
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        measurements:
          type: array
          items:
            $ref: '#/components/schemas/Measurement'
    MeasurementServiceRequest:
      type: object
      description: Encapsulates a measurement book service request. Takes a singleton along with workflow.
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        measurements:
          type: array
          items:
            $ref: '#/components/schemas/MeasurementExtended'
    
    MeasurementServiceResponse:
      type: object
      description: Encapsulates a measurement service response. Returns an array of measurements with workflow.
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        measurements:
          type: array
          items:
            $ref: '#/components/schemas/MeasurementExtended'
