openapi: 3.0.0
info:
  version: 1.0.0
  title: Get applications for inbox
  description: |
    ### API specs for inbox ###
    * Employees get applications in his inbox on which are assigned to him or on which he can take action
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
x-module: Inbox
x-common-path: 'https://raw.githubusercontent.com/egovernments/municipal-services/common-contract/docs/common-contract-v2-0-0.yml'
paths:

  /inbox/v1/_search:
    post:
      description: Returns applications to be displayed in inbox
      tags:
        - inbox-controller
      summary:  Searches applications based on given search criteria
      operationId: searchUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxRequest'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InboxResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /inbox/v1/dss/_search:
    description: Returns dss applications to be displayed in inbox
    post:
      tags:
        - inbox-controller
      summary: getChartV2 for dss applications
      operationId: getChartV2UsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxMetricCriteria'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: number
                  format: bigdecimal
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found        
  /inbox/v1/elastic/_search:
    post:
      description: Returns elastic search response to be displayed in inbox
      tags:
        - inbox-controller
      summary: Returns elastic search response
      operationId: elasticSearchUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxElasticSearchRequest'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found        
          
        

components:
  schemas:
    InboxSearchCriteria:
      type: object
      description: 'BPA application object to capture the details of land, land owners, and address of the land.'
      properties:
        tenantId:
          type: string
          description: TenantId of the user
          minLength: 1
          maxLength: 64
        processSearchCriteria:
          type: object
          items:
            $ref: '#/components/schemas/ProcessInstanceSearchCriteria'  
        moduleSearchCriteria:
          type: object
          description: Hashmap containing the module search params and values
          minLength: 1
          maxLength: 64
        offset:
          type: integer
          description: Offset of the search result
        limit:
          description: Limit of search result
          type: integer
    
    InboxElasticSearchCriteria:
      title: InboxElasticSearchCriteria
      required:
        - indexKey
        - tenantId
      type: object
      properties:
        fromDate:
          type: integer
          format: int64
        indexKey:
          type: string
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        sortOrder:
          type: string
        tenantId:
          type: string
        toDate:
          type: integer
          format: int64
    
    PlainAccessRequest:
      title: PlainAccessRequest
      type: object
      description: plain access request for inbox
      properties:
        plainRequestFields:
          type: array
          description: plain request fields
          items:
            type: string
            description: items in plain access request
        recordId:
          type: string
          description: record id for request
    
    RequestInfo:
      title: RequestInfo
      type: object
      properties:
        apiId:
          maxLength: 128
          type: string
          description: unique API ID
        ver:
          maxLength: 32
          type: string
          description: API version - for HTTP based request this will be same as used
            in path
        ts:
          type: integer
          description: time in epoch
          format: int64
        action:
          maxLength: 32
          type: string
          description: API action to be performed like _create, _update, _search (denoting
            POST, PUT, GET) or _oauth etc
        did:
          maxLength: 1024
          type: string
          description: Device ID from which the API is called
        key:
          maxLength: 256
          type: string
          description: API key (API key provided to the caller in case of server to
            server communication)
        msgId:
          maxLength: 256
          type: string
          description: Unique request message id from the caller
        requesterId:
          maxLength: 256
          type: string
          description: UserId of the user calling
        authToken:
          type: string
          description: //session/jwt/saml token/oauth token - the usual value that
            would go into HTTP bearer token
        userInfo:
          $ref: '#/components/schemas/User'
      description: RequestInfo should be used to carry meta information about the
        requests to the server as described in the fields below. All eGov APIs will
        use requestinfo as a part of the request body to carry this meta information.
        Some of this information will be returned back from the server as part of
        the ResponseInfo in the response body to ensure correlation.
    InboxElasticSearchRequest:
      title: InboxElasticSearchRequest
      type: object
      properties:
        InboxElasticSearchCriteria:
          $ref: '#/components/schemas/InboxElasticSearchCriteria'
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
    
    Role:
      title: Role
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the role.
          format: int64
        name:
          maxLength: 100
          minLength: 2
          type: string
          description: The Name of the Role.
        code:
          maxLength: 50
          minLength: 0
          type: string
          description: The Code of the Role.
        tenantId:
          maxLength: 256
          minLength: 0
          type: string
          description: Tenant ID of the Role.
    
    User:
      title: User
      type: object
      properties:
        emailId:
          maxLength: 300
          minLength: 0
          type: string
          description: email address of the authenticated user
        id:
          type: integer
          format: int64
          description: "List of system generated ids of applications."
        mobileNumber:
          maxLength: 150
          minLength: 0
          type: string
          description: mobile number of the autheticated user
        name:
          maxLength: 250
          minLength: 0
          type: string
          description: name of the user
        roles:
          type: array
          description: List of all the roles for the primary tenant
          items:
            $ref: '#/components/schemas/Role'
            
        tenantId:
          maxLength: 256
          minLength: 0
          type: string
          description: Unique Identifier of the tenant to which user primarily belongs
        type:
          maxLength: 50
          minLength: 0
          type: string
          description: type of user (if the user is a citizen/employee) 
        userName:
          maxLength: 180
          minLength: 0
          type: string
          description: Unique user name of the authenticated user
        uuid:
          maxLength: 36
          minLength: 0
          type: string
          description: System Generated User id of the authenticated user.
    
    InboxMetricCriteria:
      title: InboxMetricCriteria
      type: object
      properties:
        module:
          type: string
          description: Module name of the applications 
        tenantId:
          type: string
          description: Unique Identifier of the tenant to which inbox metric primarily belongs
   
    ProcessInstanceSearchCriteria:
      type: object
      description: |
        Schema to search process instances
      properties:
        tenantId:
          type: string
          readOnly: true
          description: The tenantIds of the applications.
          minLength: 2
          maxLength: 64
        status:
          type: array
          items:
            type: string
          description: List of statuses of pplications.
        businessIds:
          type: string
          items:
            type: string
          description: The application numbers to search
        assignee:
          type: string
          description: UUID of the assignee
          minLength: 2
          maxLength: 256
        ids:
          type: string
          items:
            type: string
          description: UUIDS of the processinstances 
          minLength: 2
          maxLength: 64
        businessService:
          type: string
          description: BusinessService (Workdflow config code) of the applications
        moduleName:
          type: string
          description: Module name of the applications 
          readOnly: true
        isProcessCountCall:
          type: string
          description: 'Source mdms master data. Which captures the source of the service request(ex:- whatsapp, ivr, Swachhata etc)'
          minLength: 2
          maxLength: 64
          example: whatsapp, ivr etc
        offset:
          type: integer
          description: Offset of the search
        limit:
          type: string
          description: Limit of the search

    InboxRequest:
      type: object
      description: Response of the FSM
      properties:
        RequestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo
        inbox:
          type: object
          $ref: '#/components/schemas/InboxSearchCriteria'
          description: Search criteria

    InboxResponse:
      type: object
      description: Response of the FSM
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
        statusMap:
          type: object
          description: map of status vs count
        items:
          type: array
          items:
            $ref: '#/components/schemas/Inbox'
        totalCount:
          type: string
          description: totalcount of records available in the system satifyig the search criteria
          
    Inbox:
      type: object
      description: >
        Inbox object
      properties:
        businessObject:
          type: string
          description: Entity object as key value pair
        ProcessInstance:
          type: object
          $ref: 'https://raw.githubusercontent.com/egovernments/core-services/master/docs/worfklow-2.0.yml#/definitions/ProcessInstance'
          description: Workflow processintance.