openapi: 3.0.0
info:
  version: "1.0.0"
  title: eGov Noc(No objection certificate) application registry
  description: |
    Noc registry store and serve the NOC related information using rest APIs
    Mainly it has below functionalities
    1. Apply for new NOC
    2. Allow user to search the existing NOC information based on roles
    3. Allow user to take action on the application based on the user role
    4. Update the NOC information for an existing application based state and role configuration
    
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
x-module: NOC
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml'
paths:
  
  /v1/noc/_create:
    post:
      tags:
        - Noc Apply
      summary: Apply for an NOC.
      description: Citizen or Employee, can apply for new build plan approval
      operationId: createUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NocRequest'
      
      
      responses:
        '200':
          description: OK
        '202':
          description: Application submitted successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NocResponse'
        '201':
          description: Created
        '400':
          description: Failed to process the application  
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /v1/noc/_update:
    post:
      summary: Update existing application.
      description: Updates a given `application` with newer details.
      x-roles: 'BPA_ARCHITECT,CITIZEN,EMPLOYEE'
      tags:
        - Noc Apply
      responses:
        '202':
          description: Application updated successfully 
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NocResponse'
        '400':
          description: Failed to update
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NocRequest'
        description: Request to update existing application details.
        required: true
  /v1/noc/_search:
    post:
      summary: Get the list of application by passing the diffrent search criteria.
      description: |
        Get the properties list based on the input parameters.
      tags:
        - Noc Apply
      operationId: searchUsingPOST
      parameters:
        - name: accountId
          in: query
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: applicationNo
          in: query
          description: application numbers
          required: false
          style: form
          schema:
            type: string
        - name: ids
          in: query
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          required: false
          style: form
          schema:
            type: integer
            format: int32
        - name: mobileNumber
          in: query
          required: false
          style: form
          schema:
            type: string
        - name: nocNo
          in: query
          description: approval number
          required: false
          style: form
          schema:
            type: string
        - name: nocType
          in: query
          description: approval type
          required: false
          style: form
          schema:
            type: string
        - name: offset
          in: query
          description: offset
          required: false
          style: form
          schema:
            type: integer
            format: int32
        - name: ownerIds
          in: query
          description: Id credential for Owners
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: source
          in: query
          description: 'Source mdms master data. Which captures the source of the service request(ex:- whatsapp, ivr, Swachhata etc)'
          required: false
          style: form
          schema:
            type: string
        - name: sourceRefId
          in: query
          description: 'Source reference Id'
          required: false
          style: form
          schema:
            type: string
        - name: status
          in: query
          description: current application status in the system records
          required: false
          style: pipeDelimited
          schema:
            type: array
            items:
              type: string
        - name: tenantId
          in: query
          description: "Unique id for a tenant."
          required: true
          style: form
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestInfoWrapper'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NocResponse'
        '201':
          description: Created
        '400':
          description: Invalid input    
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  
servers:
# Added by API Auto Mocking Plugin
  - url: 'https://egov-micro-dev.egovernments.org'
components:
  schemas:
  
   AuditDetails:
      title: AuditDetails
      type: object
      properties:
        createdBy:
          type: string
          description: username (preferred) or userid of the user that created the object
        createdTime:
          type: integer
          description: epoch of the time object is created
          format: int64
        lastModifiedBy:
          type: string
          description: username (preferred) or userid of the user that last modified the object
        lastModifiedTime:
          type: integer
          description: epoch of the time object is last modified
          format: int64
      description: Collection of audit related fields used by most models
   Document:
      title: Document
      type: object
      properties:
        additionalDetails:
          type: object
          description: Json object to capture any extra information which is not accommodated by model
        documentType:
          type: string
          description: unique document type code, should be validated with document type master
        documentUid:
          maxLength: 64
          minLength: 0
          type: string
          description: The unique id(Pancard Number,Adhar etc.) of the given Document.
        fileStoreId:
          type: string
          description: File store reference key.
        id:
          maxLength: 64
          minLength: 0
          type: string
          description: system id of the Document.
      description: This object holds list of documents attached during the transaciton for a property 
   Noc:
      title: Noc
      type: object
      properties:
        accountId:
          maxLength: 64
          minLength: 1
          type: string
          description: Initiator User UUID
        additionalDetails:
          type: object
          description: The json to capturing the custom fields
        applicationNo:
          maxLength: 64
          minLength: 1
          type: string
          description: Generate formatted Unique Identifier of the Noc. Keep the format in mdms
          readOnly: true
        applicationStatus:
          maxLength: 64
          minLength: 1
          type: string
          description: Application status should get populate from wf engine
          readOnly: true
        applicationType:
          type: string
          description: noc application type.
          enum:
            - NEW
            - PROVISIONAL
            - RENEW
        auditDetails:
          $ref: '#/components/schemas/AuditDetails'
        documents:
          type: array
          description: The documents attached by owner for exemption.
          items:
            $ref: '#/components/schemas/Document'
        id:
          maxLength: 64
          minLength: 1
          type: string
          description: Unique Identifier(UUID) of the bpa application for internal reference.
          readOnly: true
        landId:
          maxLength: 64
          minLength: 1
          type: string
          description: Unique Identifier(UUID) of the land for internal reference.
        nocNo:
          maxLength: 64
          minLength: 1
          type: string
          description: Generate Noc number based on wf status. When to generate Nocno will be depends on wf state so make it configurable at application level
          readOnly: true
        nocType:
          maxLength: 64
          minLength: 1
          type: string
          description: 'Mdms master data to configure types of noc(ex:fire noc, airport authority etc) '
        source:
          maxLength: 64
          minLength: 1
          type: string
          description: Who is creating the record in the system(ex:BPA,Property etc)
        sourceRefId:
          maxLength: 64
          minLength: 1
          type: string
          description: Unique Identifier of integrator(Source system) to link the noc application.
        status:
          type: string
          description: state of the record.
          enum:
            - ACTIVE
            - INACTIVE
        tenantId:
          maxLength: 256
          minLength: 2
          type: string
          description: Unique ULB identifier.
        workflow:
          $ref: '#/components/schemas/Workflow'
      description: NOC application object to capture the details of noc related information, landid and related documents.
   NocRequest:
      title: NocRequest
      type: object
      properties:
        Noc:
          $ref: '#/components/schemas/Noc'
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
      description: A object to bind the metadata contract and main application contract
   NocResponse:
      title: NocResponse
      type: object
      properties:
        Noc:
          type: array
          items:
            $ref: '#/components/schemas/Noc'
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        count:
          type: integer
          format: int32
      description: Contains the ResponseMetadate and the main application contract
   RequestInfo:
      title: RequestInfo
      type: object
      properties:
        action:
          type: string
          description: "Action on the application in certain"
        apiId:
          type: string
          description: "unique API ID"
        authToken:
          type: string
          description: "//session/jwt/saml token/oauth token - the usual value that would go into HTTP bearer token"
        correlationId:
          type: string
          description: "RequestInfo should be used to carry meta information about the requests to the server as described in the fields below. All eGov APIs will use requestinfo as a part of the request body to carry this meta information. Some of this information will be returned back from the server as part of the ResponseInfo in the response body to ensure correlation."
        did:
          type: string
          description: "Device ID from which the API is called"
        key:
          type: string
          description: "API key (API key provided to the caller in case of server to server communication)"
        msgId:
          type: string
          description: "message id of the request"
        ts:
          type: integer
          format: int64
          description: time in epoch
        userInfo:
          $ref: '#/components/schemas/User'
        ver:
          type: string
          description: "API version - for HTTP based request this will be same as\
            \ used in path"
   RequestInfoWrapper:
      title: RequestInfoWrapper
      type: object
      properties:
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
   ResponseInfo:
      title: ResponseInfo
      type: object
      properties:
        apiId:
          type: string
          description: "unique API ID"
        msgId:
          type: string
          description: "message id of the request"
        resMsgId:
          type: string
          description: "unique response message id (UUID) - will usually be the correlation id from the server"
        status:
          type: string
          description: current application status in the system records
        ts:
          type: integer
          format: int64
          description: time in epoch
        ver:
          type: string
          description: "API version - for HTTP based request this will be same as\
            \ used in path"
   Role:
      title: Role
      type: object
      properties:
        code:
          description: "Unique code of the role"
          type: string
        id:
          description: "List of system generated ids of applications."
          type: integer
          format: int64
        name:
          type: string
          description: name of user
        tenantId:
          type: string
          description: "Unique id for a tenant."
   User:
      title: User
      type: object
      properties:
        emailId:
          type: string
          description: Email address of the user
        id:
          description: The unique id an user.
          type: integer
          format: int64
        mobileNumber:
          type: string
          description: Mobile number ofuser the user
        name:
          type: string
          description: The full name of the user.
        roles:
          type: array
          description: List of roles that are attached to the user.
          items:
            $ref: '#/components/schemas/Role'
        tenantId:
          type: string
          description: Unique Identifier of the tenant, Like AP, AP.Kurnool etc.
        type:
          type: string
          description: System set value internally. For employee value will be always
            "EMPLOYEE". For citizen value will be "CITIZEN".
        userName:
          type: string
          description: The unique username used for user login.
        uuid:
          description: "System Generated User id of the authenticated user."
          type: string
   Workflow:
      title: Workflow
      type: object
      properties:
        action:
          maxLength: 64
          minLength: 1
          type: string
          description: Action on the application in certain
        assignes:
          type: array
          items:
            type: string
        comment:
          maxLength: 64
          minLength: 1
          type: string
          description: Comment by actor.
        documents:
          type: array
          description: Attach the workflow varification documents.
          items:
            $ref: '#/components/schemas/Document'
      description: BPA application object to capture the details of land, land owners, and address of the land.